# Generated by Django 3.0.6 on 2020-05-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
