# Generated by Django 3.0.6 on 2020-05-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_detail',
            old_name='bg',
            new_name='blood_group',
        ),
        migrations.AddField(
            model_name='user_detail',
            name='gender',
            field=models.CharField(default='other', max_length=10),
        ),
    ]
