# Generated by Django 3.0.6 on 2020-05-29 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pre_medical_history', models.TextField()),
                ('init_observation', models.TextField()),
                ('discreption', models.TextField()),
                ('Tests', models.TextField()),
                ('medication', models.TextField()),
                ('comment', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.Doctor_details')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.User_detail')),
            ],
        ),
    ]
