# Generated by Django 3.0.6 on 2020-05-31 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='report',
            table='reports',
        ),
    ]
