# Generated by Django 3.0.6 on 2020-05-31 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0003_auto_20200531_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='cmnt',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='report',
            name='dis',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='report',
            name='history',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='report',
            name='medic',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='report',
            name='observ',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='report',
            name='test',
            field=models.TextField(max_length=1000),
        ),
    ]
