# Generated by Django 3.0.6 on 2020-05-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0004_auto_20200531_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
